server:
  port: 8088

spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB

  data:
    mongodb:
      uri: mongodb+srv://crawdwallcapital_db_user:TVZ5f1QGCedSM6Zf@myappcluster.gvc03hy.mongodb.net/crawdwall?retryWrites=true&w=majority
  mail:
    host: smtp-relay.brevo.com
    port: 2525
    username: a1266e001@smtp-brevo.com
    password: bskwTb0G3jUz6kb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000

application:
  front-end-url: https://albion-portal.netlify.app
  magik-link-base-url: https://albion-api.gozade.com/magik/public/
  security:
    secret-key: DEC897856524D80723AC9FE48DDEDA830F8F40C8FC77BDBA1E81A2B88F5A41F0
    api-key: 9ikr0MsASJhgLPcOCfX1EiNbxvzIByjSvJKs4M6pZ2KVVqROl9vrsZvewWfwjZ2G
    token-expiration: 86400000

  mail:
    sender: no-reply@crowdwall.com
    support: support@crowdwall.com

  configuration:
    organization:
      name: Crawdwall
      logo: https://res.cloudinary.com/dl870gulo/image/upload/v1759977628/image_919_ykvspj.png
      supportEmail: support@crawdwal.com
      senderEmail: crawdwalls-project@crawdwall.com

  cloudinary:
    cloudName: dli16cbcp
    apiKey:  114679395854434
    apiSecret: 9yR7-eL7W6U5NrPyRrrrB6OIYP0

  sender:
    apikey: 9ikr0MsASJhgLPcOCfX1EiNbxvzIByjSvJKs4M6pZ2KVVqROl9vrsZvewWfwjZ2G

  superAdmin:
    emailAddress: admin@nominee-director.com
    password: password
    firstName: Super
    lastName: Admin
    phoneNumber: 1234567890

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method